modLoader="javafml" #mandatory
loaderVersion="${neoforge_loader_version_range}" #mandatory
license="${license}"
issueTrackerURL="${issues}" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_display_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="${homepage}" #optional
logoFile="${mod_id}.png" #optional
# credits="Thanks for this example mod goes to Java" #optional
authors="${mod_author} and other contributors" #optional
# mandatory
description="${description}"
[[dependencies.${mod_id}]]
    modId="neoforge" #mandatory
    mandatory=true #mandatory
    versionRange="${neoforge_loader_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="create"
    mandatory=false
    versionRange="${create_neoforge_range}"
    ordering="NONE"
    side="BOTH"
